# MCP Server Configuration
server:
  name: "DataVizServer"
  host: "0.0.0.0"
  port: 8000
  debug: false

# Email configuration
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "" # Set via EMAIL_USERNAME environment variable
  password: "" # Set via EMAIL_PASSWORD environment variable
  use_tls: true

# Ollama LLM configuration
ollama:
  host: "localhost"
  port: 11434
  model: "llama2"
  timeout: 30

# Authentication settings
auth:
  api_key: "" # Set via MCP_API_KEY environment variable
  require_auth: true
  allowed_origins:
    - "http://localhost:5000"
    - "https://claude.ai"

# Resource paths
paths:
  data_directory: "./data"
  scripts_directory: "./scripts"
  logs_directory: "./logs"
  output_directory: "./output"

# Tool execution settings
execution:
  script_timeout: 300 # 5 minutes
  max_output_size: 10485760 # 10MB
  allowed_extensions:
    - ".py"
    - ".csv"
    - ".txt"

# Remote MCP client settings
remote:
  enabled: true
  ssl_enabled: false
  cors_enabled: true
  max_connections: 10

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/mcp_server.log"
  max_size: 10485760 # 10MB
  backup_count: 5
